
# define the project base filename
PROJ=ccu

# list object files to be compiled into the project
OBJECTS=main.o tcnt.o gpio.o spi.o
COREOBJ=clk.o usb.o

# include all software-global make rules.
include ../global.mk

