#!/bin/bash

source proj

sed -e 's@\(Q01\)-G@\1-1@g' \
    -e 's@\(Q01\)-D@\1-4@g' \
    -e 's@\(Q01\)-S@\1-3@g' \
    -i v${ver}.net

sed -e 's@\(Q02\)-G@\1-1@g' \
    -e 's@\(Q02\)-D@\1-3@g' \
    -e 's@\(Q02\)-S@\1-2@g' \
    -i v${ver}.net

