# Makefile: all compilation and programming parameters for PPM firmware

# define the project base filename
PROJ=dds

# list object files to be compiled into the project
OBJECTS=main.o dds.o gpio.o spi.o
COREOBJ=clk.o usb.o

# include all software-global make rules.
include ../global.mk

