# Makefile: all compilation and programming parameters for PPM firmware

# define the project base filename and version.
PROJ=ppm
VER=1
REV=1

# list object files to be compiled into the project.
OBJECTS=main.o ppm.o tcnt.o gpio.o spi.o
COREOBJ=clk.o usb.o

# include all software-global make rules.
include ../global.mk

