# Makefile: all compilation and programming parameters for SCB firmware

# define the project base filename
PROJ=scb

# list object files to be compiled into the project
OBJECTS=main.o scb.o gpio.o spi.o
COREOBJ=clk.o usb.o

# include all software-global make rules.
include ../global.mk

