# Makefile: all compilation and programming parameters for SCB firmware

# define the project base filename and version.
PROJ=scb
VER=0
REV=0

# list object files to be compiled into the project.
OBJECTS=main.o scb.o gpio.o spi.o
COREOBJ=clk.o usb.o

# include all software-global make rules.
include ../global.mk

